# Generated by Django 3.0.6 on 2020-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200420_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='YanGooAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_metrika', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Code YanGoo Analytics',
            },
        ),
    ]
