# Generated by Django 3.0.6 on 2020-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_yangooanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangooanalytics',
            name='id',
        ),
        migrations.AddField(
            model_name='yangooanalytics',
            name='type_metrika',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
